Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//to access model class
using ElectronicsAppMVC.Models;

namespace ElectronicsAppMVC.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            //initialize values to a model class property
            List<Product> products = new List<Product>();
            Product product = new Product();
            product.ProductId = 1;
            product.Name = "Apple iPad";
            product.Quantity = 15.00f;
            product.Price = 89000.56f;
            product.Image = "AppleIpad.jpg";
            products.Add(product);
            Product product1 = new Product();
            product1.ProductId = 2;
            product1.Name = "Logitech Keyboard";
            product1.Quantity = 25.00f;
            product1.Price = 5000.56f;
            product1.Image = "logitech.jpg";
            products.Add(product1);
            Product product3 = new Product();
            product3.ProductId = 3;
            product3.Name = "Portable SSD";
            product3.Quantity = 5.00f;
            product3.Price = 25000.56f;
            product3.Image = "portablessd.jpg";
            products.Add(product3);
            Product product4 = new Product();
            product4.ProductId = 4;
            product4.Name = "WIFI Extender";
            product4.Quantity = 15.00f;
            product4.Price = 8000.56f;
            product4.Image = "widiextender.jpg";
            products.Add(product4);

            return View(products);
        }
        public IActionResult AboutUs() {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectronicsAppMVC.Controllers
{
    public class RazorController : Controller
    {
        //action method 
        public IActionResult RazorSyntax()
        {
            return View();
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElectronicsAppMVC.Models;
using Microsoft.Extensions.Configuration;//iconfiguration
namespace ElectronicsAppMVC.Controllers
{
    public class StudentController : Controller
    {
        private readonly IConfiguration configuration;
        string connection;
        StudentRepository repository;
        public StudentController(IConfiguration _configuration) {
            configuration = _configuration;
            connection = configuration.GetConnectionString("dbcon");
            repository = new StudentRepository();
        }
        //student details(raw data)
        public IActionResult Index()
        {
            List<Student> students = new List<Student>()
            {
                new Student(){ Id=1,FirstName="Neha",LastName="Bagul",Email="neha@cloudkampus.com",Mobile="45214",Address="Pune"},
                new Student(){ Id=2,FirstName="Amit",LastName="AAnand",Email="amit@cloudkampus.com",Mobile="7845",Address="Banglore"},
                new Student(){ Id=3,FirstName="Natasha",LastName="Dsouza",Email="natasha@cloudkampus.com",Mobile="784578",Address="Mumbai"}
            };
            return View(students);
        }

        //student details(db)
        public IActionResult Details() {
            List<Student> students = repository.GetStudents(connection);
            return View(students);
        }

        //create a new resource student
        [HttpGet]
        // http verb attribute
        //extra info about how the action method will handle the data
        //retrieve info from the server
        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        // http verb attribute
        //extra info about how the action method will handle the data
        //sending some info to the server for the processing
        public IActionResult Create(Student student) {
            //no error modelstate=true
            if (ModelState.IsValid)
            {
                return RedirectToAction("Details");
            }
            else {
                //error modelstate=false
                return View();
            }
            
        }

        [HttpGet]
        public IActionResult Register1()
        {
            return View();
        }
        //registeration page for student(tag helper)
        [HttpGet]
        public IActionResult Register() {
            return View();
        }
        [HttpPost]
        public IActionResult Register(Student student)
        {
            return View();
        }
    }
}

Views/Shared/_Advertisement.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="jumbotron">
    <h1>Google ads</h1>
    <iframe src="https://ads.google.com/home/">

    </iframe>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectronicsAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/cloudkampus-logo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Details">Student-DB</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Student-Registeration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="AboutUs">About US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ContactUs">Contact US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="RazorSyntax">Razor Syntax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="BasicHtml">Html Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="BasicHtmlBS">Html Demo-Boostrap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="BasicHtmlBSLayout">Html Demo-Boostrap Grid</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="StandardHtmlHelper">Standard Html Helper</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="StronglyHtmlHelper">Strongly Html Helper</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelper" asp-action="EditorHtmlHelper">Editor Html Helper</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ElectronicsAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>