Controllers/StateMangementController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElectronicsAppMVC.Models;

namespace ElectronicsAppMVC.Controllers
{
    public class StateMangementController : Controller
    {
        public IActionResult Index()
        {
            string username="";
            if (TempData.ContainsKey("username1")) {
                username = TempData["username1"].ToString();
            }
            return View();
        }
        public IActionResult viewDataTest()
        {
            ViewData["CompanyName"] = "CloudKampus Ltd";
            ViewData["CompanyContact"] = 89524525;
            return View();
        }
        public IActionResult viewBagTest()
        {
            ViewBag.CompanyName = "CloudKampus Ltd";
            ViewBag.CompanyContact = 89524525;
            return View();
        }
        [HttpPost]
        public IActionResult viewBagTest(User user)
        {
            ViewBag.username = user.username;
            ViewBag.password = user.passward;
            TempData["username1"] = user.username;
            if (ViewBag.username == "Admin" && ViewBag.password == "Admin123")
            {
                return RedirectToAction("Index");
            }
            else {
                ViewBag.errormessage = "Invalid Username or password";
                return View();
            }
           
            
        }
        public IActionResult reset() {
            return View();
        }
        public IActionResult HTMLBootstrapGrid()
        {
            return View();
        }
    }
}

Views/StateMangement/HTMLBootstrapGrid.cshtml
@{
    ViewData["Title"] = "HTMLBootstrapGrid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>HTMLBootstrapGrid</h1>
<style>
    .maindiv {
        border: 1px solid orange;
        border-radius: 10px;
        padding: 20px;
        background-color: #586a7a29;
    }
</style>

<h1>HTML BOOTSTRAP GRID LAYOUT SAMPLE</h1>

<!DOCTYPE html>
<html>
<head>
    <title>My Simple HTML Registraion Page Design </title>
</head>
<body>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label class="control-label" for="l1">First Name</label>
                <input class="form-control" type="text" id="txt1" name="fname" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="from-group">
                <label class="control-label" for="l2">Middle Name</label>
                <input class="form-control" type="text" id="txt2" name="fname" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="from-group">
                <label class="control-label" for="l3">Last Name</label>
                <input class="form-control" type="text" id="txt3" name="fname" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="from-group">
                <label class="control-label" for="l4">Gender</label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="from-group">
                <input type="radio" id="rad1" value="M" name="rad" />Male
            </div>
        </div>
        <div class="col-md-3">
            <div class="from-group">
                <input type="radio" id="rad2" value="F" name="rad" />Female
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l6">Address</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="text" id="txt4" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l7">PinCode</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="number" id="txt5" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l8">City</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="text" id="txt6" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l9">State</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="text" id="txt7" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l10">Mobile Numer</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" maxlength="10" type="number" id="txt8" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l5">Email</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="email" id="txt9" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l5">D.O.B</label>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="from-group">
                        <input class="form-control" type="date" id="txt10" name="fname" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l5">Experties</label>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="from-group">
                        <input type="checkbox" id="chk1" name="HTML" />HTML
                        <input type="checkbox" id="chk2" name="CSS" />CSS
                        <input type="checkbox" id="chk3" name="C#" />C#
                        <input type="checkbox" id="chk4" name="JAVA" />JAVA
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="from-group">
                        <label class="control-label" for="l6">Experience</label>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="from-group">
                        <select class="form-control">
                            <option value="1">Fresher</option>
                            <option value="2">0-1</option>
                            <option value="3">1-3</option>
                            <option value="4">3-Above</option>
                        </select>
                    </div>

                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="from-group">
                        <input type="button" class="btn-success" id="bttn1" value="Submit" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="from-group">
                        <input type="button" class="btn-danger" id="bttn2" value="Reset" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            
            <table class="table">
                <tr>
                    <th>name</th>
                </tr>
            </table>
        </div>
    </div>
    
</body>

</html>

Views/StateMangement/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View Data</h1>
<div>
    <span>Welcome : @TempData["username1"]</span>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron bg-warning">
            <h1>@ViewData["CompanyName"]</h1>
            <h1><span class="text-success">Contact Us at :</span> @ViewData["CompanyContact"]</h1>
        </div>
    </div>
</div>
<h1>View Bag</h1>
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron bg-warning">
            <h1>@ViewBag.CompanyName</h1>
            <h1><span class="text-success">Contact Us at :</span> @ViewBag.CompanyContact</h1>
        </div>
    </div>
</div>

Views/StateMangement/viewBagTest.cshtml
@model ElectronicsAppMVC.Models.User
@{
    ViewData["Title"] = "viewBagTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron bg-warning">
            <h1>@ViewBag.CompanyName</h1>
            <h1><span class="text-success">Contact Us at :</span> @ViewBag.CompanyContact</h1>
        </div>
    </div>
</div>
<hr/>
<form asp-action="viewBagTest">
    <div>
        <span class="text-danger">@ViewBag.errormessage</span>
    </div>
    <label class="control-label" asp-for="username"></label>
    <input type="text" asp-for="username" />
    <label class="control-label" asp-for="passward"></label>
    <input type="text" asp-for="passward"/>
    <input type="submit" name="login" value="login" class="btn btn-success"/>
</form>
<form asp-action="reset">
    <input type="reset" name="reset" value="reset"/>
</form>
<div class="jumbotron bg-info">
    <h1>@ViewBag.username</h1>
    <h1>@ViewBag.password</h1>
</div>

Views/StateMangement/viewDataTest.cshtml
@{
    ViewData["Title"] = "viewDataTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a asp-controller="StateMangement" asp-action="Index">View Data</a>
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron bg-warning">
            <h1>@ViewData["CompanyName"]</h1>
            <h1><span class="text-success">Contact Us at :</span> @ViewData["CompanyContact"]</h1>
        </div>
    </div>   
</div>